version: '3'

services:
  api:
    image: ${DOCKER_REPO_USER}/api:latest
    build:
      context: ./
      dockerfile: deploy/api.dockerfile
    command: uwsgi uwsgi.ini
    # volumes:
    #   - ./breastcancer:/code/breastcancer
    #   - ./ml:/code/ml
    #   - ./tests:/code/tests
    ports:
      - "8080:8080"
    environment:
      - SERVICE_PORTS=8080
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
        max_attempts: 3
        window: 120s
    networks:
      - web

  proxy:
    image: dockercloud/haproxy
    depends_on:
      - api
    environment:
      - BALANCE=leastconn
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 80:80
    networks:
      - web
    deploy:
      placement:
        constraints: [node.role == manager]

networks:
  web:
    driver: overlay
